enchants:
  antithorns:
    enabled: true # Enable/Disable the enchantment
    trigger-chance: -1 # Chance of triggering the enchantment. -1 for disabled
    table-chance: -1 # Chance of getting this enchant on a table, -1 for disabled
    enchanted-item-lore-name: '&7Anti Thorns %level%' # The lore name of the enchantment
    book-display-name: "&d&lAnti Thorns %level%" # The display name of the book which you get via the command
    cursed: false # Doesn't do anything as of now, mostly used for the API.
    treasure: false # Doesn't do anything as of now, mostly used for the API.
    rarity: VERY_RARE # COMMON, UNCOMMON, RARE, VERY_RARE; Doesn't do anything as of now, mostly used for the API.
    lore: # The lore of the book which you get via the command
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Each piece on its own has 25% to deflect"
      - "&7all thorns damage."
      - "&7Having 4 pieces will deflect 100% of thorns damage."
      - ""
      - "&6Enchantable items: &aTools"
    # If true, it will use the built-in enchantment conflicts, ex. you can't have antithorns and thorns on the same item
    # If false, it will use the conflicts from the 'conflicts' section.
    default-conflicts: true
    # Apart from the internal enchant conflicts, you can add your own here.
    # Has to be valid enchantment names. (Works for vanilla and ExtraEnchants enchantments)
    # You can find a list of enchantment names here (field):
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
    enchantable-items: []
    conflicts:
      - THORNS
  telepathy:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Telepathy %level%'
    book-display-name: "&b&lTelepathy %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically send"
      - "&7mined blocks to your inventory."
      - ""
      - "&6Enchantable items: &aTools"
    default-conflicts: true
    conflicts:
      - SILK_TOUCH
    # Can be: TOOLS, ARMOR, WEAPONS, ALL
    # or specify the type of armor, e.g. HELMET, CHESTPLATE, LEGGINGS, BOOTS, ELYTRA, SHIELD
    # or specify the type of tool, e.g. PICKAXE, AXE, SHOVEL, HOE, SWORD, BOW, FISHING_ROD
    # or specify the type of weapon, e.g. SWORD, BOW, CROSSBOW
    # The default limitation still applies if you don't specify anything.
    enchantable-items:
      - TOOLS
  plow:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Plow %level%'
    book-display-name: "&d&lPlow %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically plant seeds from hotbar."
      - "&7Will till a 3x1 area to the left of till."
      - ""
      - "&7Level 2 does 6x1 area to the left and right."
      - ""
      - "&6Enchantable items: &aHoes"
    default-conflicts: true
    conflicts: []
    enchantable-items:
      - HOE
  lavawalker:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Lava Walker %level%'
    book-display-name: "&d&lLava Walker %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more Info."
      - ""
      - "&7Will automatically replace lava to obsidian"
      - "&7when walking on it."
      - ""
      - "&6Enchantable items: &aBoots"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
    extra:
      duration: 4 # How long the obsidian will stay in seconds
  bonded:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Bonded %level%'
    book-display-name: "&d&lBonded %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will prevent the item from being dropped."
      - ""
      - "&6Enchantable items: &aTools & Armor"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  smelt:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Smelt %level%'
    book-display-name: "&d&lSmelt %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically smelt mined ores and blocks."
      - ""
      - "&6Enchantable items: &aTools"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  hasteminer:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Haste Miner %level%'
    book-display-name: "&d&lHaste Miner %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 10% chance to give Haste 1 effect for 5 seconds."
      - ""
      - "&6Enchantable items: &aPickaxes, Shovels"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  veinminer:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Vein Miner %level%'
    book-display-name: "&d&lVein Miner %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to "
      - "&7mine all adjacent ores."
      - ""
      - "&6Enchantable items: &aPickaxes"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  experienceminer:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Experience Miner %level%'
    book-display-name: "&d&lXP Miner %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to drop some"
      - "&7additional experience while mining blocks."
      - ""
      - "&6Enchantable items: &aPickaxes"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  lifesteal:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Lifesteal %level%'
    book-display-name: "&d&lLifesteal %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to heal"
      - "&7yourself for 10% of the damage dealt."
      - ""
      - "&6Enchantable items: &aSwords"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  tunnel:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Tunnel %level%'
    book-display-name: "&d&lTunnel %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Can be helpful while tunnelling."
      - ""
      - "&6Enchantable items: &aPickaxes, Shovels"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  berserk:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Berserk %level%'
    book-display-name: "&d&lBerserk %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Does less damage on full health,"
      - "&7does more damage on less health."
      - ""
      - "&6Enchantable items: &aSwords"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  disposer:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Disposer %level%'
    book-display-name: "&d&lDisposer %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Automatically destroys mined blocks."
      - ""
      - "&6Enchantable items: &aPickaxes"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  coldsteel:
    enabled: true
    trigger-chance: 5
    table-chance: 10
    enchanted-item-lore-name: '&7Cold Steel %level%'
    book-display-name: "&d&lCold Steel %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to inflict"
      - "&7slowness to attacker when being attacked."
      - ""
      - "&6Enchantable items: &aArmor"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  withering:
    enabled: true
    trigger-chance: 1
    table-chance: -1
    enchanted-item-lore-name: '&7Withering %level%'
    book-display-name: "&d&lWithering %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to inflict wither effect."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  armorbreaker:
    enabled: true
    trigger-chance: 5
    table-chance: -1
    enchanted-item-lore-name: '&7Armor Breaker %level%'
    book-display-name: "&d&lArmor Breaker %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to deal extra durability damage."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  barbarian:
    enabled: true
    trigger-chance: 5
    table-chance: -1
    enchanted-item-lore-name: '&7Barbarian %level%'
    book-display-name: "&d&lBarbarian %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to deal 1.25x damage."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  deathsiphon:
    enabled: true
    trigger-chance: 25
    table-chance: -1
    enchanted-item-lore-name: '&7Death Siphon %level%'
    book-display-name: "&d&lDeath Siphon %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Each piece has a %trigger-chance% to grant"
      - "&dRegeneration III&7 for 3 seconds."
      - ""
      - "&6Enchantable items: &aArmor"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
    extra:
      player-only: true
  batvision:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Bat Vision %level%'
    book-display-name: "&d&lBat Vision %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Grants night vision while equipped."
      - ""
      - "&6Enchantable items: &aHelmets"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  gills:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Gills %level%'
    book-display-name: "&d&lGills %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Grants water-breathing while equipped."
      - ""
      - "&6Enchantable items: &aHelmets"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  assassin:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Assassin %level%'
    book-display-name: "&d&lAssassin %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Does more damage while close and less when far."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
    extra:
      player-only: false
  turtleshell:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Turtle Shell %level%'
    book-display-name: "&d&lTurtle Shell %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Each piece makes you receive 2.5% less"
      - "&7damage when hit from behind."
      - ""
      - "&6Enchantable items: &aArmor"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  reinforced:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Reinforced %level%'
    book-display-name: "&d&lReinforced %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Each piece protects from an additional player"
      - "&7for 2.5% of the damage."
      - ""
      - "&7Receive 2.5% less damage when two players are near,"
      - "&75% less when three players are near, up to 10%."
      - ""
      - "&6Enchantable items: &aArmor"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  webbing:
    enabled: true
    trigger-chance: 1
    table-chance: -1
    enchanted-item-lore-name: '&7Webbing %level%'
    book-display-name: "&d&lWebbing %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to place "
      - "&7a web on opponents feet for %duration% seconds."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
    extra:
      duration: 3
      player-only: true
  replanter:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Replanter %level%'
    book-display-name: "&d&lReplanter %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Automatically replants seeds."
      - ""
      - "&6Enchantable items: &aHoes"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  timber:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Timber %level%'
    book-display-name: "&d&lTimber %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Automatically chops down adjacent logs."
      - ""
      - "&6Enchantable items: &aHoes"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  excavator:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    enchanted-item-lore-name: '&7Excavator %level%'
    book-display-name: "&d&lExcavator %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Mines 3x3 area in front of you."
      - ""
      - "&6Enchantable items: &aPickaxes, Shovels"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  debuffing:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Debuffing %level%'
    book-display-name: "&d&lDebuffing %level%"
    cursed: false
    treasure: false
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to remove"
      - "&7all potion effects from the opponent when"
      - "&7opponent has less than 4 hearts."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []
  essence-drain:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    enchanted-item-lore-name: '&7Essence Drain %level%'
    book-display-name: "&d&lEssence Drain %level%"
    cursed: false
    treasure: true
    rarity: VERY_RARE
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a %trigger-chance% chance to double"
      - "&7experience gained from killing mobs."
      - ""
      - "&6Enchantable items: &aWeapons"
    default-conflicts: true
    conflicts: []
    enchantable-items: []

messages:
  no-permission: "&c&lYou do not have permission to do this!"
  player-not-found: "&c&lPlayer not found."
  enchantment-list: "&9&lCurrent Enchants:\n&3&lTelepathy, Plow, Lava Walker, Bonded..."
  usage: "&c&lCommand usage: &d/&7ee <enchantment> <player>"
  enchant-removed: "&4%enchant_name% enchant has been removed"
  enchant-conflicts: "&cEnchant conflicts with one of the enchants shown below:"
  cannot-enchant-item: "&cYou cannot enchant this item."
  enchant-applied: "&aSuccessfully applied enchantment to item."
  hold-item: "&cYou must hold an item in your hand."
  reloaded: "&aSuccessfully reloaded config."

# Enchant signs work similar to EssentialsX signs.
# It supports the ExtraEnchants enchantments and vanilla ones.
# To create an enchant sign, use the following format (first line should match enchant-signs.first-line-format).
# > ENCHANT <
# ENCHANTABLE_ITEM_TYPE
# ENCHANTMENT
# COST : LEVEL
#
# Sign example:
# > ENCHANT <
#     ANY
#  TELEPATHY
#   1000 : 1
#
# Item type can be: TOOLS, ARMOR, WEAPONS, ALL
# or specify the type of armor, e.g. HELMET, CHESTPLATE, LEGGINGS, BOOTS, ELYTRA, SHIELD
# or specify the type of tool, e.g. PICKAXE, AXE, SHOVEL, HOE, SWORD, BOW, FISHING_ROD
# or specify the type of weapon, e.g. SWORD, BOW, CROSSBOW
# The default limitation still applies if you don't specify anything.
#
# Cost can be defined in money, experience or levels. (The currency symbol can be anything)
# The following formats are supported:
# - 100 : 1
# - 100$ : 1
# - 100 $ : 1
# - 100L : 1
# - 100 L : 1
# - 100XP : 1
# - 100 XP : 1
enchant-signs:
  enabled: true
  # You can add own color codes when placing it. This should be plain.
  # You can also add color format to other lines too.
  first-line-format: "> ENCHANT <"
  messages:
    sign-created: "&aSuccessfully created enchant sign."
    invalid-enchant: "&cInvalid enchantment."
    invalid-item-type: "&cInvalid item type."
    invalid-cost-level: "&cInvalid cost and level format."
    not-enough-money: "&cYou do not have enough money to purchase this enchant."
    no-item-in-hand: "&cYou must hold an item in your hand."
    cannot-enchant-item: "&cYou cannot enchant this item with this sign."
    enchant-applied: "&aSuccessfully applied enchantment."
    already-enchanted: "&cThis item is already enchanted."
    not-enough-xp: "&cYou do not have enough XP to purchase this enchant."
    not-enough-levels: "&cYou do not have enough levels to purchase this enchant."

debug: false
notify-update: true