enchants:
  telepathy:
    enabled: true
    displayname: "&b&lTelepathy I"
    lore:
      - "&7Drag book and drop on Item."
      - "&7Right click for more Info."
      - ""
      - "&7Will automatically send"
      - "&7mined blocks to your inventory."
      - ""
      - "&6Enchantable Items: &aTools"
  plow:
    enabled: true
    displayname: "&d&lPlow I"
    lore:
      - "&7Drag book and drop on Item."
      - "&7Right click for more Info."
      - ""
      - "&7Will automatically plant seeds from hotbar."
      - "&7Will till a 3x1 area to the left of till."
      - ""
      - "&6Enchantable Items: &aHoes"
  smelt:
    enabled: true
    displayname: "&d&lSmelt I"
    lore:
      - "&7Drag book and drop on Item."
      - "&7Right click for more Info."
      - ""
      - "&7Will automatically smelt mined ores and blocks."
      - ""
      - "&6Enchantable Items: &aTools"

messages:
  no-permission: "&c&lYou do not have permission to do this!"
  player-not-found: "&c&lPlayer not found."
  enchantment-list: "&9&lCurrent Enchants:\n&3&lTelepathy, Plow, Smelt"
  usage: "&c&lCommand usage: &d/&7ee <enchantment> <player>"
  enchant-removed: "&4%enchant_name% enchant has been removed"