enchants:
  telepathy:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&b&lTelepathy %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically send"
      - "&7mined blocks to your inventory."
      - ""
      - "&6Enchantable items: &aTools"
  plow:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lPlow %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically plant seeds from hotbar."
      - "&7Will till a 3x1 area to the left of till."
      - ""
      - "&6Enchantable items: &aHoes"
  lava_walker:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lLava Walker %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more Info."
      - ""
      - "&7Will automatically plant seeds from hotbar."
      - "&7Will till a 3x1 area to the left of till."
      - ""
      - "&6Enchantable items: &aBoots"
  bonded:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lBonded %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will prevent the item from being dropped."
      - ""
      - "&6Enchantable items: &aTools & Armor"
  smelt:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lSmelt %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Will automatically smelt mined ores and blocks."
      - ""
      - "&6Enchantable items: &aTools"
  haste_miner:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    displayname: "&d&lHaste Miner %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 10% chance to give Haste 1 effect for 5 seconds."
      - ""
      - "&6Enchantable items: &aPickaxes, Shovels"
  veinminer:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    displayname: "&d&lVein Miner %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 10% chance to mine all adjacent ores."
      - ""
      - "&6Enchantable items: &aPickaxes"
  experience_miner:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    displayname: "&d&lXP Miner %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 10% to drop some additional experience."
      - "&7while mining blocks."
      - ""
      - "&6Enchantable items: &aPickaxes"
  lifesteal:
    enabled: true
    trigger-chance: 10
    table-chance: -1
    displayname: "&d&lLifesteal %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 10% to heal yourself for 10% of the"
      - "&7damage dealt."
      - ""
      - "&6Enchantable items: &aSwords"
  tunnel:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lLifesteal %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Can be helpful while tunnelling."
      - ""
      - "&6Enchantable items: &aPickaxes, Shovels"
  berserk:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lBerserk %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Does less damage on full health,"
      - "&7does more damage on less health."
      - ""
      - "&6Enchantable items: &aSwords"
  disposer:
    enabled: true
    trigger-chance: -1
    table-chance: -1
    displayname: "&d&lDisposer %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Automatically destroys mined blocks."
      - ""
      - "&6Enchantable items: &aPickaxes"
  cold_steel:
    enabled: true
    trigger-chance: 5
    table-chance: 10
    displayname: "&d&lCold Steel %level%"
    lore:
      - "&7Drag book and drop on item."
      - "&7Right click for more info."
      - ""
      - "&7Has a 5% chance to inflict slowness."
      - ""
      - "&6Enchantable items: &aArmor"
messages:
  no-permission: "&c&lYou do not have permission to do this!"
  player-not-found: "&c&lPlayer not found."
  enchantment-list: "&9&lCurrent Enchants:\n&3&lTelepathy, Plow, Lava Walker, Bonded"
  usage: "&c&lCommand usage: &d/&7ee <enchantment> <player>"
  enchant-removed: "&4%enchant_name% enchant has been removed"

debug: false