main: me.m0dii.extraenchants.ExtraEnchants
bootstrapper: me.m0dii.extraenchants.ExtraEnchantsBootstrapper
name: M0-ExtraEnchants
author: M0dii
version: 3.6.2
api-version: 1.21.3
commands:
  extraenchant:
    permission: extraenchants.command.enchant
    description: Enchant command.
    aliases: [ee, extraenchants, eench]
  unenchant:
    permission: extraenchants.command.unenchant
    description: Unenchant command.
    aliases: [unench, unen, ue]

dependencies:
  server:
    Residence:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true