main: me.m0dii.extraenchants.ExtraEnchants
name: M0-ExtraEnchants
author: M0dii
version: ${version}
api-version: 1.21.3
softdepend: [Residence, Vault, PlaceholderAPI]
commands:
  extraenchant:
    permission: extraenchants.command.enchant
    description: Enchant command.
    aliases: [ee, extraenchants, eench]
  unenchant:
    permission: extraenchants.command.unenchant
    description: Unenchant command.
    aliases: [unench, unen, ue]