main: me.m0dii.extraenchants.ExtraEnchants
name: M0-ExtraEnchants
author: M0dii
version: 3.4.0
api-version: 1.16
commands:
  extraenchant:
    permission: extraenchants.command.enchant
    description: Enchant command.
    aliases: [ee, extraenchants, eench]
  unenchant:
    permission: extraenchants.command.unenchant
    description: Unenchant command.
    aliases: [unench, unen, ue]