main: me.M0dii.ExtraEnchants.ExtraEnchants
name: M0-ExtraEnchants
author: M0dii
version: 1.2
api-version: 1.16
depend: [Residence]
commands:
  extraenchant:
    permission: extraenchants.command.enchant
    description: Enchant command.
    aliases: [ee, ae]
  unenchant:
    permission: extraenchants.command.unenchant
    description: Unenchant command.
    aliases: [unench, unen, ue]